# Generated by Django 4.0.5 on 2022-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='topic'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('published', 'Yayinlandi'), ('draft', 'Taslak'), ('deleted', 'Silindi')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='status',
            field=models.CharField(choices=[('published', 'Yayinlandi'), ('draft', 'Taslak'), ('deleted', 'Silindi')], default='draft', max_length=10),
        ),
    ]
