# Generated by Django 4.0.5 on 2022-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_alter_category_cover_image_alter_category_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('deleted', 'Silindi'), ('draft', 'Taslak'), ('published', 'Yayinlandi')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='topic'),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='status',
            field=models.CharField(choices=[('deleted', 'Silindi'), ('draft', 'Taslak'), ('published', 'Yayinlandi')], default='draft', max_length=10),
        ),
    ]
